In [31]:
import cv2 as cv
import numpy as np
import random

img = cv.imread("assets/logo.jpg",-1)
print(img[200:500,500:700])

[[[ 37 123 245]
  [ 37 123 245]
  [ 35 124 245]
  ...
  [ 60  58  58]
  [ 60  58  58]
  [ 60  58  58]]

 [[ 37 123 245]
  [ 37 123 245]
  [ 35 124 245]
  ...
  [ 60  58  58]
  [ 60  58  58]
  [ 60  58  58]]

 [[ 37 124 244]
  [ 37 123 245]
  [ 37 123 245]
  ...
  [ 60  58  58]
  [ 60  58  58]
  [ 60  58  58]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [32]:
print(img.shape)
print(img[257][500:510])
print(img[257,500:510])


(995, 1000, 3)
[[ 38 117 244]
 [ 39 118 245]
 [ 37 118 245]
 [ 37 118 245]
 [ 39 118 245]
 [ 39 118 245]
 [ 39 118 245]
 [ 37 118 245]
 [ 37 119 244]
 [ 37 119 244]]
[[ 38 117 244]
 [ 39 118 245]
 [ 37 118 245]
 [ 37 118 245]
 [ 39 118 245]
 [ 39 118 245]
 [ 39 118 245]
 [ 37 118 245]
 [ 37 119 244]
 [ 37 119 244]]


In [45]:
for i in range(500,600):
    for j in range(img.shape[1]): #all width values
        # height, width, channel
        img[i][j] = [random.randrange(255), random.randrange(255), random.randrange(255)]

cv.imshow("image", img)
        
cv.waitKey(0)
cv.destroyAllWindows()

In [34]:
img = cv.imread("assets/logo.jpg",-1)
tag = img[500:900, 200:450]
# tag = cv.rotate(tag, cv.ROTATE_180)
img[200:600, 650:900] = tag

cv.imshow("Image_tagged", img)
cv.waitKey(0)
cv.destroyAllWindows()

In [52]:
## rescale  
img2 = cv.imread("assets/logo.jpg",-1)

def rescale(img2, scale):
    height = int(img2.shape[0]* scale)
    width = int(img2.shape[1]* scale)

    dimensions = (width, height)
    
    return cv.resize(img2, dimensions, interpolation=cv.INTER_AREA)
    
img2 = rescale(img2, 0.5)
cv.imshow("image", img2)
cv.waitKey(0)
cv.destroyAllWindows()