In [1]:
import numpy as np

b = np.arange(40)
b = b.reshape((4,2,5))
b

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [2]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [3]:
b.flatten(order="F")

array([ 0, 10, 20, 30,  5, 15, 25, 35,  1, 11, 21, 31,  6, 16, 26, 36,  2,
       12, 22, 32,  7, 17, 27, 37,  3, 13, 23, 33,  8, 18, 28, 38,  4, 14,
       24, 34,  9, 19, 29, 39])

In [4]:
b.flatten(order="A")

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [5]:
b.flatten(order="K")

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [6]:
###Ravel usually returns a view into the existing array (sometimes it returns a copy). Flatten returns a new array. 
##note 2:
# flatten always returns a copy.
# ravel returns a view of the original array whenever possible. This isn't visible in the printed output, but if you modify the array returned by ravel, it may modify the entries in the original array. If you modify the entries in an array returned from flatten this will never happen. ravel will often be faster since no memory is copied, but you have to be more careful about modifying the array it returns.
# reshape((-1,)) gets a view whenever the strides of the array allow it even if that means you don't always get a contiguous array.
 

In [7]:
###ravel unlike flatten is a function and can be used like np.ravel or ndarray.ravel
np.ravel(b)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [8]:
np.ravel(b,order="F")

array([ 0, 10, 20, 30,  5, 15, 25, 35,  1, 11, 21, 31,  6, 16, 26, 36,  2,
       12, 22, 32,  7, 17, 27, 37,  3, 13, 23, 33,  8, 18, 28, 38,  4, 14,
       24, 34,  9, 19, 29, 39])

In [11]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])