In [5]:
import numpy as np

##1dimension
a = np.random.randint(100,size=(10,))
a

array([84, 37, 40, 13, 99, 34, 22, 96, 91, 52])

In [8]:
a.size

10

In [10]:
b = np.insert(a,1,170)

In [11]:
b.size

11

In [13]:
np.insert(a,(1,3),110)

array([ 84, 110,  37,  40, 110,  13,  99,  34,  22,  96,  91,  52])

In [14]:
np.insert(a,(1,3),(110,140))

array([ 84, 110,  37,  40, 140,  13,  99,  34,  22,  96,  91,  52])

In [16]:
##2dimension
a = np.array([[4,5],[10,12]])
a

array([[ 4,  5],
       [10, 12]])

In [17]:
np.insert(a,1,25)  ##if no axis= is given it will flatten the data first

array([ 4, 25,  5, 10, 12])

In [18]:
np.insert(a,1,25,axis=0)  ##broadcasting 

array([[ 4,  5],
       [25, 25],
       [10, 12]])

In [19]:
np.insert(a,1,25,axis=1)

array([[ 4, 25,  5],
       [10, 25, 12]])

In [30]:
x = np.insert(a,1,[25,50],axis=1)

In [33]:
y = np.insert(a,[1],[[25],[50]],axis=1)  ##same as above

In [34]:
np.array_equal(x,y)

True

In [23]:
##more info
help(np.insert) 

Help on function insert in module numpy:

insert(arr, obj, values, axis=None)
    Insert values along the given axis before the given indices.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : int, slice or sequence of ints
        Object that defines the index or indices before which `values` is
        inserted.
    
        .. versionadded:: 1.8.0
    
        Support for multiple insertions when `obj` is a single scalar or a
        sequence with one element (similar to calling insert multiple
        times).
    values : array_like
        Values to insert into `arr`. If the type of `values` is different
        from that of `arr`, `values` is converted to the type of `arr`.
        `values` should be shaped so that ``arr[...,obj,...] = values``
        is legal.
    axis : int, optional
        Axis along which to insert `values`.  If `axis` is None then `arr`
        is flattened first.
    
    Returns
    -------
    out : ndarray
        A

In [35]:
###append
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
np.append(a,1234)

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10, 1234])

In [41]:
np.concatenate((a,np.arange(4)))  ##flashback

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  0,  1,  2,  3])

In [44]:
##2D
a = np.random.randint(-5,5,(2,2))
a

array([[ 2, -5],
       [ 2, -4]])

In [49]:
np.append(a,[[3,4]],axis=0)

array([[ 2, -5],
       [ 2, -4],
       [ 3,  4]])

In [52]:
np.append(a,[[3],[4]],axis=1)

array([[ 2, -5,  3],
       [ 2, -4,  4]])

In [53]:
a = np.array([[1,2],[3,4]])
a


array([[1, 2],
       [3, 4]])

In [54]:
np.delete(a,1)

array([1, 3, 4])

In [58]:
np.delete(a,1,axis=0)

array([[1, 2]])

In [56]:
np.delete(a,1,axis=1)

array([[1],
       [3]])