In [4]:
import numpy as np

a = np.random.randint(1,5,(2,2))
a

array([[3, 3],
       [1, 3]])

In [7]:
b = np.linalg.inv(a)  ##inverse of the matrix a

In [19]:
np.dot(a,b)  ##should be close to identity matrix

array([[1.00000000e+00, 0.00000000e+00],
       [2.77555756e-17, 1.00000000e+00]])

In [15]:
np.eye(3,4,2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [16]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [17]:
np.allclose(np.dot(a,b),np.eye(2))   ###returns true if two values are close within a tolerance

True

In [21]:
help(np.linalg.inv)

Help on function inv in module numpy.linalg:

inv(a)
    Compute the (multiplicative) inverse of a matrix.
    
    Given a square matrix `a`, return the matrix `ainv` satisfying
    ``dot(a, ainv) = dot(ainv, a) = eye(a.shape[0])``.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Matrix to be inverted.
    
    Returns
    -------
    ainv : (..., M, M) ndarray or matrix
        (Multiplicative) inverse of the matrix `a`.
    
    Raises
    ------
    LinAlgError
        If `a` is not square or inversion fails.
    
    See Also
    --------
    scipy.linalg.inv : Similar function in SciPy.
    
    Notes
    -----
    
    .. versionadded:: 1.8.0
    
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    Examples
    --------
    >>> from numpy.linalg import inv
    >>> a = np.array([[1., 2.], [3., 4.]])
    >>> ainv = inv(a)
    >>> np.allclose(np.dot(a, ainv), np.eye(2))
    True
    >>> np.allclose(np.dot(ainv, a), 