In [4]:
import numpy as np

a= np.array([[10,20],[30,40]])
b = np.array([[1,2],[3,4]])

In [6]:
a * b  ##normal array multi

array([[ 10,  40],
       [ 90, 160]])

In [9]:
a.dot(b)  ##matrix multiply

array([[ 70, 100],
       [150, 220]])

In [18]:
c = np.arange(10,14).reshape(2,2)
np.dot(a,b,out=c)
c

array([[ 70, 100],
       [150, 220]])

In [22]:
help(np.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to
      :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
      preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of
      `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    It uses an optimized BLAS library when possible (see `numpy.linalg`).
    
    Parameters
    ----------
    a 

In [24]:
a = np.matrix("1 2;3 4")
a

matrix([[1, 2],
        [3, 4]])

In [26]:
b = np.matrix("10 20;30 40")
b

matrix([[10, 20],
        [30, 40]])

In [27]:
a*b  ##now it's a real matrix muliplication

matrix([[ 70, 100],
        [150, 220]])

In [28]:
a + b

matrix([[11, 22],
        [33, 44]])

In [30]:
a.T

matrix([[1, 3],
        [2, 4]])

In [32]:
a = np.matrix("1 2;3 4;5 6")  ##matrix is always 2D unlike array
a

matrix([[1, 2],
        [3, 4],
        [5, 6]])