In [3]:
import numpy as np

a = np.array([[1,2],[3,4]])

In [4]:
np.linalg.matrix_power(a,2)

array([[ 7, 10],
       [15, 22]])

In [5]:
np.dot(a,a)  ##same as abobe

array([[ 7, 10],
       [15, 22]])

In [6]:
np.linalg.matrix_power(a,3)

array([[ 37,  54],
       [ 81, 118]])

In [7]:
np.linalg.matrix_power(a,0)

array([[1, 0],
       [0, 1]])

In [8]:
np.linalg.matrix_power(a,-2)   ##reverese it then power it to 2

array([[ 5.5 , -2.5 ],
       [-3.75,  1.75]])

In [10]:
b = np.linalg.inv(a)      ##same as above  
np.dot(b,b)

array([[ 5.5 , -2.5 ],
       [-3.75,  1.75]])