In [3]:
import pandas as pd
import numpy as np

In [72]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [43]:
np.random.rand(5)

array([0.34079914, 0.4091615 , 0.95211429, 0.72269753, 0.46664734])

In [15]:
np.random.rand(5,3)

array([[0.39288669, 0.23565533, 0.23503891],
       [0.78935793, 0.54221022, 0.9039234 ],
       [0.02895942, 0.36770781, 0.47792466],
       [0.64239267, 0.38477271, 0.98046478],
       [0.46879178, 0.10111357, 0.14478941]])

In [71]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    .. note::
        New code should use the
        `~numpy.random.Generator.standard_normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribu

In [45]:
np.random.randn(5,3)

array([[-1.53884864, -0.61127395,  2.54624266],
       [ 1.51106498,  0.01770847, -0.86453572],
       [ 0.59384825, -1.60613763,  0.13308892],
       [ 1.59989294,  0.78175296, -0.8855386 ],
       [-0.2060833 ,  0.56616553,  0.32324486]])

In [76]:
np.random.ranf((5,2,3))  ## alias of random_sample 

array([[[0.13738383, 0.10417467, 0.45912785],
        [0.27173063, 0.27361192, 0.14783406]],

       [[0.53745292, 0.32602147, 0.21546832],
        [0.37668492, 0.27437567, 0.48781528]],

       [[0.02607991, 0.69729177, 0.93828019],
        [0.931536  , 0.73531241, 0.46067933]],

       [[0.0924322 , 0.05349899, 0.83923427],
        [0.09296065, 0.18910005, 0.46085203]],

       [[0.26647635, 0.62334133, 0.60665842],
        [0.60201403, 0.58962954, 0.70890825]]])

In [56]:
help(np.random.random_sample)

Help on built-in function random_sample:

random_sample(...) method of numpy.random.mtrand.RandomState instance
    random_sample(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0).
    
    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` multiply
    the output of `random_sample` by `(b-a)` and add `a`::
    
      (b - a) * random_sample() + a
    
    .. note::
        New code should use the `~numpy.random.Generator.random`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    
    Returns
    -------
    out : float or ndarray of floats
        Array of random float

In [70]:
np.random.random_sample((5,3,2))

array([[[0.5040143 , 0.32917021],
        [0.57880412, 0.6789623 ],
        [0.7150048 , 0.50538971]],

       [[0.2468357 , 0.61073178],
        [0.49360493, 0.84196366],
        [0.88191468, 0.16083424]],

       [[0.79560822, 0.04663746],
        [0.89011286, 0.34434937],
        [0.97564714, 0.37687625]],

       [[0.31283896, 0.61042019],
        [0.10565868, 0.80473027],
        [0.95431192, 0.71215585]],

       [[0.2225293 , 0.05964561],
        [0.79730591, 0.44420083],
        [0.37945845, 0.95665766]]])

In [64]:
np.random.random_sample((5,3,2)) -10

array([[[-9.48159755, -9.73120234],
        [-9.61398135, -9.14517536],
        [-9.24977577, -9.16765015]],

       [[-9.16133056, -9.65719386],
        [-9.93300194, -9.1986079 ],
        [-9.37345659, -9.01519503]],

       [[-9.1198129 , -9.39031561],
        [-9.72966626, -9.64419757],
        [-9.53150198, -9.45845596]],

       [[-9.42705357, -9.00649536],
        [-9.22373404, -9.90489899],
        [-9.46332167, -9.72762165]],

       [[-9.29226169, -9.75030853],
        [-9.18625043, -9.70341446],
        [-9.31071941, -9.35867361]]])

In [50]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the `~numpy.random.Generator.randint`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to

In [65]:
np.random.randint(90,100,size=(5,2,2))

array([[[98, 92],
        [92, 94]],

       [[95, 97],
        [96, 94]],

       [[91, 90],
        [96, 92]],

       [[90, 94],
        [90, 96]],

       [[95, 96],
        [95, 91]]])