In [103]:
import numpy as np

a= np.array([[1,2],[3,4]])
b= np.array([[5,6]])
np.concatenate((a,b))


array([[1, 2],
       [3, 4],
       [5, 6]])

In [104]:
###concat methods

a = np.random.randint(-4,8,(3,2))
b= np.random.randint(-7,12,(2,2))
print(a)
print(b)
print("\nand concat res is:")
c=np.full_like(np.random.randint(2,90,(5,2)),4)
np.concatenate((a,b),out=c)   ##out must be defined before and should have same dimension and same size
c

[[ 1  1]
 [ 4 -3]
 [ 7  5]]
[[-5 10]
 [11  6]]

and concat res is:


array([[ 1,  1],
       [ 4, -3],
       [ 7,  5],
       [-5, 10],
       [11,  6]])

In [105]:
a = np.arange(6)
a = a.reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [106]:
b = np.arange(10)
b = b.reshape(5,2)

In [107]:
np.concatenate((a,b))

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [108]:
np.concatenate((a,b),axis=1)  ##error 

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 5

In [ ]:
a = np.arange(6).reshape(2,3)
b = np.arange(10).reshape(2,5)

np.concatenate((a,b),axis=1)    ##axis= 1 ,it checks on columns so we need to have same number of rows and vice versa for axis=0                  
                        



In [109]:
a= np.array([[1,2],[3,4]])
b= np.array([[5,6]])
np.concatenate((a,b.T),axis=1)   ##because of transpose changing shape ,now only works with axis=1 option

array([[1, 2, 5],
       [3, 4, 6]])

In [110]:
a = np.arange(5)
b = np.arange(6)
c = np.arange(6)

In [111]:
np.vstack((a,c))  ##error because both must have same size and dimension

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 6

In [ ]:
##vstack when combining two 1dimension matrix ,make a 2d output unlike concat 
#for 2Dimension+ work the same as concatenate with axis=0
also
np.vstack((b,c))

In [ ]:
np.concatenate((a,b))

In [ ]:
a = np.arange(5)
b = np.arange(6)
c = np.arange(6)

##hstack is like concat with axis=0 for 1Dimension and is like concat with axis=1 for 2Dimension+

In [ ]:
np.hstack((a,b))

In [112]:
a= np.array([[1,2],[3,4]])
b= np.array([[5,6]])
np.concatenate((a,b.T),axis=1) 

array([[1, 2, 5],
       [3, 4, 6]])

In [113]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

In [114]:
####split methods
a = np.random.randint(100,size=(10,))
a

array([58, 93, 69, 11, 50, 52, 80, 56, 52, 88])

In [115]:
np.split(a,2)

[array([58, 93, 69, 11, 50]), array([52, 80, 56, 52, 88])]

In [116]:
a = np.random.randint(5,75,(4,5))
a

array([[ 9,  8, 26, 57, 36],
       [51, 30, 74, 55, 33],
       [ 9, 66, 67, 72, 18],
       [42, 11, 33, 44, 46]])

In [117]:
e,b,*c = np.split(a,4)
np.split(a,4)  ##default is axis=0 so we need multiplier of 4 rows for this to work

[array([[ 9,  8, 26, 57, 36]]),
 array([[51, 30, 74, 55, 33]]),
 array([[ 9, 66, 67, 72, 18]]),
 array([[42, 11, 33, 44, 46]])]

In [118]:
e

array([[ 9,  8, 26, 57, 36]])

In [125]:
c

[array([[ 9, 66, 67, 72, 18]]), array([[42, 11, 33, 44, 46]])]

In [134]:
a = np.random.randint(100,size=(3,6))
np.split(a,3,axis=1)  ##split to 3parts based on number of columns

[array([[30, 74],
        [59, 10],
        [66, 46]]),
 array([[64, 76],
        [70,  9],
        [54, 92]]),
 array([[44, 62],
        [67, 73],
        [12, 41]])]

In [135]:
np.hsplit(a,3)  ##hsplit same as split with axis=1 default

[array([[30, 74],
        [59, 10],
        [66, 46]]),
 array([[64, 76],
        [70,  9],
        [54, 92]]),
 array([[44, 62],
        [67, 73],
        [12, 41]])]

In [136]:
np.vsplit(a,3)  ##vsplit same as split except it has no axis= parameter

[array([[30, 74, 64, 76, 44, 62]]),
 array([[59, 10, 70,  9, 67, 73]]),
 array([[66, 46, 54, 92, 12, 41]])]

In [137]:
np.split(a,3)

[array([[30, 74, 64, 76, 44, 62]]),
 array([[59, 10, 70,  9, 67, 73]]),
 array([[66, 46, 54, 92, 12, 41]])]