In [42]:
import numpy as np


b = np.arange(8).reshape(2,4)
print(b)
b.shape

[[0 1 2 3]
 [4 5 6 7]]


(2, 4)

In [43]:
b.transpose()

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [44]:
##transpose is a function so we can use it like this
np.transpose(b)  ##default is axes=(1,0)

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [45]:
np.transpose(b).shape

(4, 2)

In [46]:
np.transpose(b,axes=(0,1))  ##no change

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [47]:
a =np.arange(1,25).reshape(2,3,4)
print(a)
a.shape


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


(2, 3, 4)

In [48]:
a.transpose()

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [49]:
a.transpose().shape

(4, 3, 2)

In [53]:
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [55]:
a.transpose((0,2,1))

array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]],

       [[13, 17, 21],
        [14, 18, 22],
        [15, 19, 23],
        [16, 20, 24]]])

In [57]:
a.shape


(2, 3, 4)

In [56]:
np.transpose(a,axes=(2,0,1)) ##reshape to (4,2,3)

array([[[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]],

       [[ 4,  8, 12],
        [16, 20, 24]]])

In [60]:
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [65]:
a.shape

(2, 3, 4)

In [61]:
## you can use T attribute for transposing but won't take axes= arguement
print(a.T.shape)
a.T

(4, 3, 2)


array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [89]:
np.transpose(a,)

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [101]:
print(a.shape)
a

(2, 3, 4)


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [96]:
##just takes 2 arguement
print(a.swapaxes(0,1).shape)
a.swapaxes(0,1)

(3, 2, 4)


array([[[ 1,  2,  3,  4],
        [13, 14, 15, 16]],

       [[ 5,  6,  7,  8],
        [17, 18, 19, 20]],

       [[ 9, 10, 11, 12],
        [21, 22, 23, 24]]])

In [99]:
np.transpose(a,axes=(1,0,2))  ##same result as above ,only it need to give more than 2 arg for 3d array

array([[[ 1,  2,  3,  4],
        [13, 14, 15, 16]],

       [[ 5,  6,  7,  8],
        [17, 18, 19, 20]],

       [[ 9, 10, 11, 12],
        [21, 22, 23, 24]]])

In [100]:
np.reshape(a,(3,2,4))

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [80]:
np.swapaxes(a,1,0)

array([[[ 1,  2,  3,  4],
        [13, 14, 15, 16]],

       [[ 5,  6,  7,  8],
        [17, 18, 19, 20]],

       [[ 9, 10, 11, 12],
        [21, 22, 23, 24]]])

In [85]:
c = np.array([[3,4,6,7,]])
c.shape


(1, 4)

In [71]:
c.transpose()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
np.swapaxes(c,1,0)

array([[3],
       [4],
       [6],
       [7]])

In [87]:
np.transpose(c)

array([[3],
       [4],
       [6],
       [7]])