#### Random Forest Algorithm
https://www.youtube.com/watch?v=eM4uJ6XGnSM&list=PLEiEAq2VkUULNa6MHQAZSOBxzB6HHFXj4&index=5

In [56]:
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
np.random.seed(0)

In [57]:
iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [58]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [59]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [60]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [61]:
df = pd.DataFrame(iris.data, columns=iris["feature_names"])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [62]:
df["species"] = pd.Categorical.from_codes(iris.target, iris.target_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [63]:
##approx 75% data goes to train
df["is_train"] = np.random.uniform(0,1,len(df)) <= .75
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

       species  is_train  
0       setosa      True  
1       setosa      True  
2       setosa      True  
3       setosa      True  
4       setosa      True  
..         ...       ...  
145  virginica      True  
146  virginica      True  
147  virginica     False  
148  virginica      True  
149  virginica     False  

[150 rows x 6 columns]

In [64]:
# df.drop(columns=["is_train"],axis=1, inplace=True)
# df

In [65]:
filt = df["is_train"]
train, test = df[filt==True], df[filt==False]
len(test),len(train)

(32, 118)

In [66]:
features = df.columns[:4]
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [67]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [68]:
train["species"]

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
141    virginica
142    virginica
145    virginica
146    virginica
148    virginica
Name: species, Length: 118, dtype: category
Categories (3, object): ['setosa', 'versicolor', 'virginica']

In [69]:
##practice
# labels, uniques = pd.factorize(test["petal width (cm)"], sort=True)
# labels, uniques

In [70]:
##converting species into digits
y = pd.factorize(train["species"])[0]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [71]:
##practice my way of choosing y but we need to add one more column
# df["targets"] = iris.target
# train, test = df[df["is_train"]==True], df[df["is_train"]==False]

# y = train["targets"]
# print(y,"\nnumpy array format:")
# y = y.to_numpy()
# y

In [72]:
train[features]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
141                6.9               3.1                5.1               2.3
142                5.8               2.7                5.1               1.9
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
148                6.2               3.4                5.4               2.3

[118 rows x 4 columns]

In [73]:
clf = RandomForestClassifier(n_jobs=2, random_state=0)
clf.fit(train[features], y)

RandomForestClassifier(n_jobs=2, random_state=0)

In [74]:
test[features].head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
7                 5.0               3.4                1.5               0.2
8                 4.4               2.9                1.4               0.2
10                5.4               3.7                1.5               0.2
13                4.3               3.0                1.1               0.1
17                5.1               3.5                1.4               0.3

In [75]:
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [76]:
clf.predict_proba(test[features])[:10]

array([[1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.95, 0.05, 0.  ],
       [1.  , 0.  , 0.  ],
       [0.99, 0.01, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ]])

In [77]:
class_names = iris.target_names
class_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [78]:
preds = clf.predict(test[features])
preds

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [81]:
pred_labels = class_names[preds]
pred_labels[:5]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa'], dtype='<U10')

In [82]:
test["species"].head()

7     setosa
8     setosa
10    setosa
13    setosa
17    setosa
Name: species, dtype: category
Categories (3, object): ['setosa', 'versicolor', 'virginica']

In [83]:
pd.crosstab(test["species"], pred_labels, rownames=["actual species"], colnames=["predicted species"])

predicted species  setosa  versicolor  virginica
actual species                                  
setosa                 13           0          0
versicolor              0           5          2
virginica               0           0         12

In [84]:
acc = f"{(pred_labels == test['species']).sum() / len(test) * 100} %"
acc

'93.75 %'

In [85]:
np.random.randint(0,5, (1,4))

array([[4, 0, 2, 3]])

In [86]:
###deploy model on random data
preds = clf.predict([[5.0,3.6,1.4,2.0],[5.0,3.6,1.4,2.0]])
class_names = iris.target_names
pred_labels = class_names[preds]
pred_labels

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array(['setosa', 'setosa'], dtype='<U10')

In [87]:
preds = clf.predict(np.random.randint(0,5, (6,4)))
class_names = iris.target_names
pred_labels = class_names[preds]
pred_labels

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array(['virginica', 'setosa', 'setosa', 'setosa', 'virginica', 'setosa'],
      dtype='<U10')